name: Run Unit Test
on:
  push:
    branches-ignore:    
      - develop
defaults:
  run:
    working-directory: /home/runner/work/testing_json_env/testing_json_env/go/src/github.com/testing_json_env
env:
  GOPATH: /home/runner/work/testing_json_env/testing_json_env/go
  GOPRIVATE: github.com/*
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout testing_json_env
      uses: actions/checkout@v3
      with:
        path: go/src/github.com/testing_json_env

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Compile code and run tests
      run: |
        make test
